% !Rnw root = ../article.Rnw

Although epidemics are by definition a process that evolves over time, epidemics, including the recent COVID-19, often need to be compared in a less time focused, or even time-free way to understand the processes at play. Additionally, many tools to examine the quantity of the population in each state along the infection process (for example: quantity of suspectible vs infected vs recovered individuals) don't always as intelligently capture the natural connections between the proportion of individuals in these states. Tools in \pkg{EpiCompare} attempt to give the user the ability to extend their toolkit to evaluate epidemics to also include time-free approaches and in this section we present benefits of the time-free analysis, with 1) motivation for time-free analysis through $R_0$ (the initial reproduction number), 2) time-free visualization tools for 3-state models (e.g. SIR models), and 3) potential for similar analysis for models with more states (e.g. SEIR models).

\SweaveInput{ch3.1-r0.Rnw}
\SweaveInput{ch3.2-ternary.Rnw}
\SweaveInput{ch3.3-simplex-and-beyond.Rnw}
