// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// l2filamentdist
double l2filamentdist(NumericMatrix m1, NumericMatrix m2);
RcppExport SEXP _EpiCompare_l2filamentdist(SEXP m1SEXP, SEXP m2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type m1(m1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type m2(m2SEXP);
    rcpp_result_gen = Rcpp::wrap(l2filamentdist(m1, m2));
    return rcpp_result_gen;
END_RCPP
}
// distalongpath
List distalongpath(NumericMatrix m1);
RcppExport SEXP _EpiCompare_distalongpath(SEXP m1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type m1(m1SEXP);
    rcpp_result_gen = Rcpp::wrap(distalongpath(m1));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_EpiCompare_l2filamentdist", (DL_FUNC) &_EpiCompare_l2filamentdist, 2},
    {"_EpiCompare_distalongpath", (DL_FUNC) &_EpiCompare_distalongpath, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_EpiCompare(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
