# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

l2filamentdist <- function(m1, m2) {
    .Call('_EpiCompare_l2filamentdist', PACKAGE = 'EpiCompare', m1, m2)
}

distalongpath <- function(m1) {
    .Call('_EpiCompare_distalongpath', PACKAGE = 'EpiCompare', m1)
}

